version: '3.7'

services:
  redis:
    build: ./redis
    container_name: redis
    hostname: redis
    networks:
      private-dockers-network:
        ipv4_address: 172.100.0.2
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf

  mysql:
    build: ./mysql/mysql56
    container_name: mysql
    hostname: mysql
    networks:
      private-dockers-network:
        ipv4_address: ${MYSQL_IP}
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./mysql/mysql56/data:/var/lib/mysql
      - ./mysql/mysql56/my.cnf:/etc/mysql/my.cnf
    privileged: true

  nginx:
    build: ./nginx
    container_name: nginx
    hostname: nginx
    networks:
      private-dockers-network:
        ipv4_address: 172.100.0.4
    ports:
      - "80:80"
    volumes:
      - ./nginx/etc/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - /Users/taorong/dev/work/devmp.noahorganic:/usr/share/nginx/html/devmp.noahorganic
      - /Users/taorong/dev/work/mylovegy-examination:/usr/share/nginx/html/exam.dev.com

  php7:
    build: ./php/php7
    container_name: php7
    hostname: php7
    networks:
      private-dockers-network:
        ipv4_address: 172.100.0.5
    ports:
      - "9001:9001"
    volumes:
      - /Users/taorong/dev/work/devmp.noahorganic:/usr/share/nginx/html/devmp.noahorganic
      - /Users/taorong/dev/work/mylovegy-examination:/usr/share/nginx/html/exam.dev.com

  php5:
    build: ./php/php5
    container_name: php5
    hostname: php5
    networks:
      private-dockers-network:
        ipv4_address: 172.100.0.6
    ports:
      - "9000:9000"
    volumes:
      - /Users/taorong/dev/work/devmp.noahorganic:/usr/share/nginx/html/devmp.noahorganic
      - ./php/php5/php.ini:/usr/local/etc/php/php.ini

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - ./elasticsearch/data:/usr/share/elasticsearch/data:z
    networks:
      private-dockers-network:
        ipv4_address: ${ES_IP}
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_USER: elastic
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node

  mongo:
    image: mongo
    container_name: mongo
    networks:
      private-dockers-network:
        ipv4_address: 172.100.0.11
    ports:
      - "27017:27017"

  prometheus-node-exporter-demo:
    image: prom/node-exporter
    container_name: prometheus-node-exporter-demo
    hostname: prometheus-node-exporter-demo
    networks:
      private-dockers-network:
        ipv4_address: 172.100.0.12
    ports:
      - 9100:9100
    volumes:
      - ./prometheus/node-exporter/proc:/host/proc:ro
      - ./prometheus/node-exporter/sys:/host/sys:ro

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    networks:
      private-dockers-network:
        ipv4_address: 172.100.0.13
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    networks:
      private-dockers-network:
        ipv4_address: 172.100.0.14
    ports:
      - 3000:3000
    volumes:
      - ./prometheus/grafana-storage:/var/lib/grafana

  jaeger-tracing:
    image: jaegertracing/all-in-one
    container_name: jaeger-tracing
    hostname: jaeger-tracing
    networks:
      private-dockers-network:
        ipv4_address: 172.100.0.15
    ports:
      - 16686:16686   #web
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 14268:14268
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: "9411"
    volumes:
      - ./prometheus/grafana-storage:/var/lib/grafana

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,z
    networks:
      private-dockers-network:
        ipv4_address: 172.100.0.23
    extra_hosts:
      - elasticsearch:${ES_IP}
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
    networks:
      private-dockers-network:
        ipv4_address: 172.100.0.17
    extra_hosts:
      - elasticsearch:${ES_IP}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

#  demo:
#    build: ./demo
#    networks:
#      private-dockers-network:
#        ipv4_address: 172.100.0.18
#    ports:
#      - 9012:8080

  openldap:
    container_name: openldap
    image: osixia/openldap:1.5.0
    networks:
      private-dockers-network:
        ipv4_address: 172.100.0.19
    volumes:
      - ./openldap/data/ldap:/var/lib/ldap
      - ./openldap/data/slapd.d:/etc/ldap/slapd.d
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=baidu
      - LDAP_DOMAIN=baidu.com
      - LDAP_ADMIN_PASSWORD=asdasdasd
      - LDAP_READONLY_USER=false
      #- LDAP_READONLY_USER_USERNAME=readonly
      #- LDAP_READONLY_USER_PASSWORD=readonly

  # ldap 管理页面
  openldap_phpldapadmin:
    container_name: openldap_phpldapadmin
    image: osixia/phpldapadmin:0.9.0
    networks:
      private-dockers-network:
        ipv4_address: 172.100.0.20
    ports:
      - "9081:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=172.100.0.20
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap

  # 自助密码服务
  openldap_self-service-password:
    container_name: openldap_self-service-password
    image: tiredofit/self-service-password:5.1.2
    networks:
      private-dockers-network:
        ipv4_address: 172.100.0.21
    ports:
      - "9082:80"
    environment:
      - LDAP_SERVER=openldap
      - LDAP_STARTTLS=false
      - LDAP_BINDDN=cn=admin,dc=baidu,dc=com
      - LDAP_BINDPASS=asdasdasd
      - LDAP_BASE_SEARCH=dc=baidu,dc=com
      - MAIL_FROM_NAME=统一认证服务
      - MAIL_FROM=devops@baidu.com
      - MAIL_SIGNATURE=\n\n\n欢迎使用统一认证服务~~
      - NOTIFY_ON_CHANGE=true
      - SMTP_AUTH_ON=true
      - SMTP_AUTOTLS=true
      - SMTP_HOST=smtp.exmail.qq.com
      - SMTP_SECURE_TYPE=ssl
      - SMTP_PORT=465
      - SMTP_USER=devops@baidu.com
      - SMTP_PASS=
      - IS_BEHIND_PROXY=true
      - SITE_URL=http://localhost:9082/
    depends_on:
      - openldap





networks:
  private-dockers-network:
    ipam:
      config:
        - subnet: 172.100.0.0/16
